# Generated by Django 4.1.5 on 2023-01-28 02:11

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('harga', models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(999999), django.core.validators.MinValueValidator(1)])),
                ('stock', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(999), django.core.validators.MinValueValidator(0)])),
            ],
            options={
                'db_table': 'product',
            },
        ),
        migrations.CreateModel(
            name='Transaksi',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created', models.DateTimeField(blank=True, default=datetime.datetime(2023, 1, 28, 9, 11, 43, 127072))),
            ],
            options={
                'db_table': 'transaksi',
            },
        ),
        migrations.CreateModel(
            name='Quantity',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(999), django.core.validators.MinValueValidator(1)])),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_product', to='product.product')),
                ('transaksi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_transaksi', to='product.transaksi')),
            ],
            options={
                'db_table': 'quantity',
            },
        ),
    ]
